spring.application.name=BookMarket

# 기본 profile
spring.profiles.active=local

# JPA 공통 설정
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
