# =========================
# Server (Railway)
# =========================
server.port=${PORT:8080}
server.servlet.context-path=/BookMarket

# =========================
# MariaDB (Railway)
# =========================
spring.datasource.url=jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# =========================
# JPA (Railway)
# =========================
spring.jpa.show-sql=false
